# Generated by Django 4.0 on 2024-05-16 23:23

from django.db import migrations, models
import django.utils.timezone
import reservationApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0002_client_order_service_session_worker_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(null=True, validators=[reservationApp.validators.validate_time_interval]),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=16),
        ),
    ]
