# Generated by Django 4.0 on 2024-05-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0003_order_created_session_date_session_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='surname',
        ),
    ]
