# Generated by Django 4.0 on 2024-05-17 00:13

from django.db import migrations, models
import reservationApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0006_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(validators=[reservationApp.validators.validate_time_interval]),
        ),
    ]
