# Generated by Django 4.0 on 2024-05-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0009_alter_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservationApp.order'),
        ),
        migrations.AddField(
            model_name='session',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservationApp.worker'),
        ),
    ]
