# Generated by Django 4.0 on 2024-05-17 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0010_session_order_session_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationApp.order'),
        ),
        migrations.AlterField(
            model_name='session',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationApp.worker'),
        ),
    ]
